### ISSUE TITLE
pygame.error: Failed loading libmpg123-0.dll: The specified module could not be found.

### ISSUE THREAD

**Issue by yashprsin** [PacktPublishing/hands-on-exploratory-data-analysis-with-python#1]
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:/Users/jo/PycharmProjects/test1/Code with harry/HealthyPro.py", line 30, in <module>
    pygame.mixer.music.load("water.mp3")
pygame.error: Failed loading libmpg123-0.dll: The specified module could not be found.

[``](### **url**)

**Comment by amireallyadev** [comment]
@8deadlyjoker  which folder in this repository are you running? It seems you are running a file named `HealthPro.py`, which I could not find in this repository?

**Comment by sureshHARDIYA** [comment]
This issue is not associated with the codebase associated with this book. The error is from `pygame`. Please take this issue with `pygame` repository.
