### ISSUE TITLE
regarding weekday_name

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/hands-on-exploratory-data-analysis-with-python#6]
When I was trying to run the line which has "weekday_name" , I am getting an error. I guess it should be changed to "x.day_name"

**Comment by sureshHARDIYA** [comment]
@KeerthanaPeddireddy  could you be more explicit which file were you able to run? which notebook?

**Comment by sureshHARDIYA** [comment]
Closing this issue due to --less interactivity
