### ISSUE TITLE
chapter 7: countplot() got multiple values for argument 'data'

### ISSUE THREAD

**Issue by andysingal** [PacktPublishing/hands-on-exploratory-data-analysis-with-python#7]
```
fig, ax = plt.subplots(1, 2, figsize = (7, 5))
titanic["Pclass"].value_counts().plot.bar(color = "skyblue", ax = ax[0])
ax[0].set_title("Number Of Passengers By Pclass")
ax[0].set_ylabel("Population")
sns.countplot("Pclass", hue = "Survived", data = titanic, ax = ax[1])
ax[1].set_title("Pclass: Survived vs Dead")
plt.show()
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[10], line 6
      3 ax[0].set_title("Number Of Passengers By Pclass")
      4 ax[0].set_ylabel("Population")
----> 6 sns.countplot("Pclass", hue = "Survived", data = titanic)
      7 ax[1].set_title("Pclass: Survived vs Dead")
      8 plt.show()

TypeError: countplot() got multiple values for argument 'data'
```

**Comment by gokcenazakyol** [comment]
I have got the same error, any solutions?

**Comment by sureshHARDIYA** [comment]
@gokcenazakyol  let me have a look, probably you are using some latest version of library. I will push a fix with never version, today.

**Comment by gokcenazakyol** [comment]
I think we solved the problem. 

sns.countplot("Pclass", hue = "Survived", data = titanic, ax = ax[1])

In that line, we need to define x="Pclass", otherwise, (I think) we try to reassign data value and that cause the error.

**Comment by sureshHARDIYA** [comment]
Feel free to create a pull request.

**Comment by SanjayBhat-S** [comment]
> I think we solved the problem.
> 
> sns.countplot("Pclass", hue = "Survived", data = titanic, ax = ax[1])
> 
> In that line, we need to define x="Pclass", otherwise, (I think) we try to reassign data value and that cause the error.

Thank you for this solution @gokcenazakyol .

**Comment by dtiwariHO** [comment]
try :  sns.countplot(x='Survived', data=titanic, ax=ax[1])
